# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LetItGo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LetItGo
# Required by RNFirebase
pod 'Firebase/Core', '~> 6.3.0'
pod 'Firebase/Firestore', '~> 6.3.0'
pod 'Firebase/Auth', '~> 6.3.0'

  target 'LetItGo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LetItGoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'LetItGo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LetItGo-tvOS



end
